version: "3"

services:
    app-myfitness:
        build: .
        restart: always
        ports:
            - "8000:8000" #pc:container
        volumes:
            - .:/var/www
        networks:
            - bridge_connection

    db-myfitness:
        image: mysql:5.7
        restart: always
        ports:
            - "5306:3306"
        environment:
            - MYSQL_DATABASE=myfitness
            - MYSQL_ROOT_PASSWORD=123
        volumes:
            - ./.docker/mysql/db_data:/var/lib/mysql
        networks:
            - bridge_connection

networks:
    bridge_connection:
        driver: bridge

volumes:
    db_data: