version: '3'

services:

  app:
    build: .
    container_name: lh-app
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: nginx
    container_name: lh-nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: mysql
    container_name: lh-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=myfitness
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: lh-redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge